spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/galaxiaweek3?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 309231

  jpa:
    hibernate:
      ddl-auto: none  # create / update / validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
